### ISSUE TITLE
GPU codec error

### ISSUE THREAD

**Issue by km23630** [abhiTronix/vidgear#103]
my code
```
output_params = {"-vcodec": "hevc_nvenc", "-input_framerate": fps}
        writer = WriteGear(output_filename=self.out_path,
                           compression_mode=True,
                           logging=False,
                           **output_params)
```

Error message
```
WriteGear :: ERROR :: BrokenPipeError caught, Wrong values passed to FFmpeg Pipe, Kindly Refer Docs!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/vidgear/gears/writegear.py", line 230, in write
    self.__process.stdin.write(frame.tostring())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:
```

I'm trying to write a video using writeGear in docker environment, but using codecs like h264_nvenc, hevc_nvenc, I get that error.

### Acknowledgment

- [x] A brief but descriptive Title of your issue
- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [x] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).
- [x] I have read the [Contributing Guidelines](https://github.com/abhiTronix/vidgear/blob/master/contributing.md).

### Environment

* VidGear version:
* Branch: 
* Python version: 3.6.9
* pip version: pip 19.2.3 
* Operating System and version: ubuntu 18.04
* nvidia driver: 418.87.01
* CUDA Version: 10.1
* running on nvidia-docker

### Expected Behavior
Video created normally.

### Actual Behavior
error

### Steps to reproduce

cpu acceleration like libx264 works fine.
nv-codec-headers installed.
Reinstall ffmpeg

**Comment by abhiTronix** [comment]
> self.__process.stdin.write(frame.tostring())

@km23630 This is wrong. You don't need to convert the frame to a string before giving it to WriteGear writer, just give the raw frame. **Kindly comprehend [WriteGear: Compression Mode Wiki](https://github.com/abhiTronix/vidgear/wiki/Compression-Mode:-FFmpeg#compression-mode-built-upon-ffmpeg) before using it in your own code.**

> I'm trying to write a video using writeGear in docker environment, but using codecs like h264_nvenc, hevc_nvenc, I get that error.

@km23630 **Missing Information.** Kindly use `h264_nvenc` instead of `hevc_nvenc` and **turn `logging = True` in your code and then paste the terminal message here.** I would like to see what is the real error message.

**Comment by km23630** [comment]
```
__main__ :: INFO :: successfully loaded a model
__main__ :: INFO :: start importing video writer
WriteGear :: DEBUG :: Compression Mode is enabled therefore checking for valid FFmpeg executables.
WriteGear :: DEBUG :: {'-vcodec': 'h264_nvenc', '-input_framerate': '30.0'}
Helper :: DEBUG :: Final FFmpeg Path: ffmpeg
Helper :: DEBUG :: FFmpeg validity Test Passed!
Helper :: DEBUG :: Found valid FFmpeg Version: `b'3.4.6-0ubuntu0.18.04.1'` installed on this system
WriteGear :: DEBUG :: Found valid FFmpeg executables: `ffmpeg`.
WriteGear :: DEBUG :: Compression Mode is configured properly!
__main__ :: INFO :: successfully imported a video writer
__main__ :: INFO :: start building a videoPipe
__main__ :: INFO :: successfully built a videoPipe
__main__ :: INFO :: batch:   0%|          | 0/228 [00:00<?, ?it/s]
2020-01-29 04:26:33.730124: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
2020-01-29 04:26:33.949513: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
__main__ :: INFO :: batch:   0%|          | 1/228 [00:08<32:49,  8.68s/it]
WriteGear :: DEBUG :: InputFrame => Height:720 Width:1280 Channels:3
WriteGear :: DEBUG :: Setting Input FrameRate = 30.0
WriteGear :: DEBUG :: Executing FFmpeg command: `ffmpeg -y -f rawvideo -vcodec rawvideo -s 1280x720 -pix_fmt bgr24 -framerate 30.0 -i - -vcodec h264_nvenc /workspace/tmp/pycharm_project_30/out.mp4`
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: 663552 kb/s
    Stream #0:0: Video: rawvideo (BGR[24] / 0x18524742), bgr24, 1280x720, 663552 kb/s, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (h264_nvenc))
[h264_nvenc @ 0x555c6181b7c0] Failed creating CUDA context for NVENC: 0x2
[h264_nvenc @ 0x555c6181b7c0] No NVENC capable devices found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
WriteGear :: ERROR :: BrokenPipeError caught, Wrong values passed to FFmpeg Pipe, Kindly Refer Docs!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/vidgear/gears/writegear.py", line 230, in write
    self.__process.stdin.write(frame.tostring())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/tmp/pycharm_project_30/inference-video.py", line 122, in video_masking_writer
    writer.write(frame)
  File "/usr/local/lib/python3.6/dist-packages/vidgear/gears/writegear.py", line 235, in write
    raise ValueError #for testing purpose only
ValueError

__main__ :: INFO :: batch:   1%|          | 2/228 [00:09<23:20,  6.20s/it]
```

this is my error code.

I didn't convert to string and passed numpy array as it is.

**Comment by km23630** [comment]
I solved this problem.

It is estimated that gpu is out of memory.

The problem was caused by TensorFlow taking up too much memory 
and it worked fine when I inserted the gpu memory dynamic allocation code.

**Comment by abhiTronix** [comment]
> I solved this problem.
>The problem was caused by TensorFlow taking up too much memory

@km23630 Glad to hear that and a good catch. You can also use powerful [Netgear API](https://github.com/abhiTronix/vidgear/wiki/NetGear) to stream video frames to another machine and save video there.

> [h264_nvenc @ 0x555c6181b7c0] Failed creating CUDA context for NVENC: 0x2
> [h264_nvenc @ 0x555c6181b7c0] No NVENC capable devices found

@km23630 You also need [NVIDIA VIDEO CODEC SDK](https://developer.nvidia.com/nvidia-video-codec-sdk)

> In addition my GPU is Tesla T4

Then `H.265 (HEVC)` is the fasted encoder for your system. Kindly use that instead of `H264 NVENC`
