### ISSUE TITLE
Stablilizer Error: (-215:Assertion failed) count >= 0 && count2 == count in function 'cv::RANSACPointSetRegistrator::run'

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/vidgear#172]
## Description

**Issue by @Nizcik_twitter**

I am trying to stabilize live video feed and I think this is amazing tool for that. However I am running to issue where stabilization fails due to OpenCV error and I am not sure how to troubleshoot further. I am not experienced at all on python or coding so I apologize if there is obvious steps that I should have taken. I am on Ryzen 3600 CPU and windows 10 - Python 3.9 and openCV 4.4.0. This happens every time immediately when I block the view of camera resulting in black screen.

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear).
- [x] I have read the [Issue Guidelines](https://abhitronix.github.io/vidgear/contribution/issue/#submitting-an-issue-guidelines).

### Environment

* VidGear version:  0.1.9
* Branch:  PyPi
* Python version:  3.9
* PiP version:  latest
* Operating System and version: windows 10

### Expected Behavior

No Error with blank frame.

### Actual Behavior

Here is the error:
```sh
CamGear :: DEBUG :: Enabling Threaded Queue Mode for the current video source!
Traceback (most recent call last):
File "C:\programs\Stabilizer\stabilizer.py", line 26, in <module>
stabilized_frame = stab.stabilize(frame)
File "C:\Programs\Python39\lib\site-packages\vidgear\gears\stabilizer.py", line 194, in stabilize
self.generate_transformations() # generate transformations
File "C:\Programs\Python39\lib\site-packages\vidgear\gears\stabilizer.py", line 233, in generate_transformations
transformation = cv2.estimateAffinePartial2D(
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-qjdp5db9\opencv\modules\calib3d\src\ptsetreg.cpp:174: error: (-215:Assertion failed) count >= 0 && count2 == count in function 'cv::RANSACPointSetRegistrator::run'
```

### Possible Fix

None

### Steps to reproduce

Try this video: https://raw.githubusercontent.com/abhiTronix/Imbakup/master/Images/example_empty_train_input.mp4 with Stabilizer class.

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/4f93df0a44345139b58f3180c2068c8f2e49e756**
