### ISSUE TITLE
[Bug] NetGear: Bidirectional Video-Frame Transfer broken with frame compression

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/vidgear#226]
## Description

[Video-Frames Transfer in Bidirectional Mode](https://abhitronix.github.io/vidgear/latest/gears/netgear/advanced/bidirectional_mode/#using-bidirectional-mode-for-video-frames-transfer) and also MultiClients Mode is broken when [frame compression is enabled](https://abhitronix.github.io/vidgear/latest/gears/netgear/advanced/compression/#frame-compression-for-netgear-api).

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear).
- [x] I have read the [Issue Guidelines](https://abhitronix.github.io/vidgear/contribution/issue/#submitting-an-issue-guidelines).

### Environment

* VidGear version:  v0.2.1
* Branch:  master
* Python version:  all
* PiP version:  all
* Operating System and version: all

### Expected Behavior

Seamless Bidirectional Video-Frame Transfer with frame compression.

#### Client End(Credit https://stackoverflow.com/questions/68049432/vidgear-bidirectional-mode-gives-errors):
```sh
/home/name/PycharmProjects/socket_opencv/bin/python /home/name/PycharmProjects/zoom_clone/VidGear2.py
20:32:30 :: NetGear :: WARNING :: Protocol is not supported or not provided. Defaulting to `tcp` protocol!
20:32:30 :: NetGear :: DEBUG :: Bi-Directional Data Transmission is enabled for this connection!
20:32:30 :: NetGear :: DEBUG :: Reliable transmission is enabled for this pattern with max-retries: 3 and timeout: 4.0 secs.
20:32:30 :: NetGear :: DEBUG :: Threaded Queue Mode is enabled by default for this connection.
20:32:30 :: NetGear :: DEBUG :: Successfully Binded to address: tcp://*:5555 with pattern: 0.
20:32:30 :: NetGear :: DEBUG :: JPEG Frame-Compression is activated for this connection with Quality:`90`%, Fastdct:`enabled`, and Fastupsample:`disabled`.
20:32:30 :: NetGear :: DEBUG :: Multi-threaded Receive Mode is successfully enabled.
20:32:30 :: NetGear :: DEBUG :: Unique System ID is 3E2E9.
20:32:30 :: NetGear :: DEBUG :: Receive Mode is now activated.
20:32:44 :: NetGear :: CRITICAL :: No response from Server(s), Reconnecting again...
20:32:46 :: NetGear :: ERROR :: Address already in use
Traceback (most recent call last):
  File "/home/name/PycharmProjects/socket_opencv/lib/python3.8/site-packages/vidgear/gears/netgear.py", line 873, in __recv_handler
    self.__msg_socket.bind(self.__connection_address)
  File "/home/name/PycharmProjects/socket_opencv/lib/python3.8/site-packages/zmq/sugar/socket.py", line 172, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
Exception in thread NetGear:
Traceback (most recent call last):
  File "/home/name/PycharmProjects/socket_opencv/lib/python3.8/site-packages/vidgear/gears/netgear.py", line 873, in __recv_handler
    self.__msg_socket.bind(self.__connection_address)
  File "/home/name/PycharmProjects/socket_opencv/lib/python3.8/site-packages/zmq/sugar/socket.py", line 172, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
```

#### Server end:

```sh
20:32:26 :: NetGear :: WARNING :: Protocol is not supported or not provided. Defaulting to `tcp` protocol!
20:32:26 :: NetGear :: DEBUG :: Bi-Directional Data Transmission is enabled for this connection!
20:32:26 :: NetGear :: DEBUG :: Reliable transmission is enabled for this pattern with max-retries: 3 and timeout: 4.0 secs.
20:32:26 :: NetGear :: DEBUG :: Successfully connected to address: tcp://localhost:5555 with pattern: 0.
20:32:26 :: NetGear :: DEBUG :: JPEG Frame-Compression is activated for this connection with Quality:`90`%, Fastdct:`enabled`, and Fastupsample:`disabled`.
20:32:26 :: NetGear :: DEBUG :: Unique System ID is AEE6E.
20:32:26 :: NetGear :: DEBUG :: Send Mode is successfully activated and ready to send data.
20:32:30 :: NetGear :: CRITICAL :: No response from Client, Reconnecting again...
Traceback (most recent call last):
  File "/home/name/PycharmProjects/zoom_clone/VidGear1.py", line 32, in <module>
    recv_data = server.send(frame) #message = target_data
  File "/home/name/PycharmProjects/socket_opencv/lib/python3.8/site-packages/vidgear/gears/netgear.py", line 1201, in send
    recv_json = self.__msg_socket.recv_json(flags=self.__msg_flag)
  File "/home/name/PycharmProjects/socket_opencv/lib/python3.8/site-packages/zmq/sugar/socket.py", line 782, in recv_json
    return self._deserialize(msg, lambda buf: jsonapi.loads(buf, **kwargs))
  File "/home/name/PycharmProjects/socket_opencv/lib/python3.8/site-packages/zmq/sugar/socket.py", line 607, in _deserialize
    return load(recvd)
  File "/home/name/PycharmProjects/socket_opencv/lib/python3.8/site-packages/zmq/sugar/socket.py", line 782, in <lambda>
    return self._deserialize(msg, lambda buf: jsonapi.loads(buf, **kwargs))
  File "/home/name/PycharmProjects/socket_opencv/lib/python3.8/site-packages/zmq/utils/jsonapi.py", line 56, in loads
    s = s.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

### Possible Fix

Bypass `return_data` in following lines:
https://github.com/abhiTronix/vidgear/blob/eb19b9ce96061c09b5fe4c3ee63d84c940a19af2/vidgear/gears/netgear.py#L945-L953

### Steps to reproduce

https://abhitronix.github.io/vidgear/latest/gears/netgear/advanced/bidirectional_mode/#using-bidirectional-mode-for-video-frames-transfer

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/b1fa9d3e5a9b879dd36c69667fbf00c3136e1f35**
