### ISSUE TITLE
[Bug]: Netgear_Async with WriteGear not working as expected

### ISSUE THREAD

**Issue by ginwakeup** [abhiTronix/vidgear#326]
### Description

Hello,
I'm experiencing a crash while sending and then writing video through NetGear_Async and WriteGear and the error is not clear.

This is my code:

client.py
```python
from vidgear.gears.asyncio import NetGear_Async
from vidgear.gears import WriteGear

import cv2
import asyncio

client = NetGear_Async(
    address="192.168.0.12",
    port="8081",
    protocol="tcp",
    pattern=2,
    receive_mode=True,
    logging=True,
).launch()


writer = WriteGear(output_filename="Output.mp4", logging=True)


async def main():
    async for frame in client.recv_generator():
        writer.write(frame)
        cv2.imshow("Output Frame", frame)
        key = cv2.waitKey(1) & 0xFF
        await asyncio.sleep(0)


if __name__ == "__main__":
    asyncio.set_event_loop(client.loop)
    try:
        client.loop.run_until_complete(main())
    except (KeyboardInterrupt, SystemExit):
        pass

    cv2.destroyAllWindows()
    client.close()
    writer.close()
```

server.py
```python
import os
import asyncio

from vidgear.gears.asyncio import NetGear_Async


if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(__file__))
    INPUT = "test_video.mp4"
    server = NetGear_Async(
        source=INPUT,
        address="192.168.0.12",
        port="8081",
        protocol="tcp",
        pattern=2,
        logging=True,
    ).launch()

    asyncio.set_event_loop(server.loop)
    try:
        server.loop.run_until_complete(server.task)
    except (KeyboardInterrupt, SystemExit):
        pass
    finally:
        server.close()
```

The video streams fine until the few last frames.
The output is 1.8MB against the original 5.3 and it doesn't play.

This is the client logs:

```
11:54:43 ::    Helper     ::   INFO   :: Running VidGear Version: 0.2.6
11:54:43 :: NetGear_Async ::   INFO   :: Using `Loop` event loop for this process.
11:54:43 :: NetGear_Async ::  DEBUG   :: Launching NetGear_Async asynchronous generator!
11:54:43 ::   WriteGear   ::  DEBUG   :: Compression Mode is enabled therefore checking for valid FFmpeg executable.
11:54:43 ::   WriteGear   ::  DEBUG   :: Output Parameters: {}
11:54:43 ::    Helper     ::  DEBUG   :: Final FFmpeg Path: ffmpeg
11:54:43 ::    Helper     ::  DEBUG   :: FFmpeg validity Test Passed!
11:54:43 ::    Helper     ::  DEBUG   :: Found valid FFmpeg Version: `b'5.0.1'` installed on this system
11:54:43 ::   WriteGear   ::  DEBUG   :: Found valid FFmpeg executable: `ffmpeg`.
11:54:43 ::   WriteGear   ::  DEBUG   :: Compression Mode with FFmpeg backend is configured properly.
11:54:43 :: NetGear_Async ::  DEBUG   :: Successfully binded to address: tcp://192.168.0.12:8081 with pattern: 2.
11:54:43 :: NetGear_Async :: CRITICAL :: Receive Mode is activated successfully!
11:54:53 ::   WriteGear   ::  DEBUG   :: InputFrame => Height:720 Width:1280 Channels:3
11:54:53 ::   WriteGear   ::  DEBUG   :: Executing FFmpeg command: `ffmpeg -y -f rawvideo -vcodec rawvideo -s 1280x720 -pix_fmt bgr24 -i - -vcodec libx264 -crf 18 -preset fast /Users/Iacopo/Documents/GitHub/gunner/gunner/netgear/Output.mp4`
ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 13.1.6 (clang-1316.0.21.2)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: 552960 kb/s
  Stream #0:0: Video: rawvideo (BGR[24] / 0x18524742), bgr24, 1280x720, 552960 kb/s, 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
[libx264 @ 0x113f053f0] using cpu capabilities: ARMv8 NEON
[libx264 @ 0x113f053f0] profile High 4:4:4 Predictive, level 3.1, 4:4:4, 8-bit
[libx264 @ 0x113f053f0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=15 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/Users/Iacopo/Documents/GitHub/gunner/gunner/netgear/Output.mp4':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv444p(tv, progressive), 1280x720, q=2-31, 25 fps, 12800 tbn
    Metadata:
      encoder         : Lavc59.18.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
Traceback (most recent call last):     0kB time=00:00:00.08 bitrate=   4.8kbits/s speed=0.0781x    
  File "client.py", line 44, in <module>
    client.loop.run_until_complete(main())
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "client.py", line 27, in main
    async for frame in client.recv_generator():
  File "/Users/Iacopo/Documents/GitHub/gunner/venv/lib/python3.8/site-packages/vidgear/gears/asyncio/netgear_async.py", line 555, in recv_generator
    datamsg_encoded = await asyncio.wait_for(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
(venv) Iacopo@MacBook-Pro netgear % frame=   67 fps=4.0 q=-1.0 Lsize=    1740kB time=00:00:02.56 bitrate=5567.6kbits/s speed=0.155x    
video:1738kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.089490%
[libx264 @ 0x113f053f0] frame I:8     Avg QP:15.22  size: 96547
[libx264 @ 0x113f053f0] frame P:28    Avg QP:19.69  size: 22807
[libx264 @ 0x113f053f0] frame B:31    Avg QP:21.05  size: 11884
[libx264 @ 0x113f053f0] consecutive B-frames: 32.8% 14.9%  4.5% 47.8%
[libx264 @ 0x113f053f0] mb I  I16..4: 19.5% 48.0% 32.5%
[libx264 @ 0x113f053f0] mb P  I16..4:  6.7% 21.5%  1.8%  P16..4: 21.1% 10.8%  4.6%  0.0%  0.0%    skip:33.6%
[libx264 @ 0x113f053f0] mb B  I16..4:  2.6%  7.7%  1.6%  B16..8: 25.5%  9.9%  0.8%  direct: 7.4%  skip:44.5%  L0:57.6% L1:32.8% BI: 9.6%
[libx264 @ 0x113f053f0] 8x8 transform intra:61.1% inter:55.1%
[libx264 @ 0x113f053f0] coded y,u,v intra: 66.5% 43.1% 38.1% inter: 16.7% 8.8% 7.3%
[libx264 @ 0x113f053f0] i16 v,h,dc,p: 22% 25% 11% 41%
[libx264 @ 0x113f053f0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 20% 21% 17%  6%  7%  7%  8%  8%  8%
[libx264 @ 0x113f053f0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 21% 17% 12%  7%  9%  9%  7% 10%  8%
[libx264 @ 0x113f053f0] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x113f053f0] ref P L0: 84.4% 15.6%
[libx264 @ 0x113f053f0] ref B L0: 92.4%  7.6%
[libx264 @ 0x113f053f0] ref B L1: 95.6%  4.4%
[libx264 @ 0x113f053f0] kb/s:5311.62
```

Seems like it gets stuck. The client.py process is not actually closed.

server logs:
```
11:54:53 ::    Helper     ::   INFO   :: Running VidGear Version: 0.2.6
11:54:53 ::    CamGear    ::  DEBUG   :: Enabling Threaded Queue Mode for the current video source!
11:54:53 :: NetGear_Async ::   INFO   :: Using `Loop` event loop for this process.
11:54:53 :: NetGear_Async ::  DEBUG   :: Creating NetGear_Async asynchronous server handler!
11:54:53 :: NetGear_Async ::  DEBUG   :: Successfully connected to address: tcp://192.168.0.12:8081 with pattern: 2.
11:54:53 :: NetGear_Async :: CRITICAL :: Send Mode is successfully activated and ready to send data!
11:54:55 :: NetGear_Async ::  DEBUG   :: Terminating various Send Mode Processes. Please wait.
11:54:55 ::    CamGear    ::  DEBUG   :: Terminating processes.
11:54:55 ::   VideoGear   ::  DEBUG   :: Terminating VideoGear.
11:54:55 :: NetGear_Async :: CRITICAL :: Send Mode successfully terminated!
```

I am running on MacOS M1 Monterey 12.4.

Any ideas?

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Expected behaviour

The video is written until the end.

### Actual behaviour

The video doesn't get written and the client process gets stuck on FFmpeg command.

### Steps to reproduce

- Download simple mp4 video
- Create client and server with Netgear async + WriteGear as stated on documentation
- Observe the incomplete output

### Terminal log output

```shell
11:54:43 ::    Helper     ::   INFO   :: Running VidGear Version: 0.2.6
11:54:43 :: NetGear_Async ::   INFO   :: Using `Loop` event loop for this process.
11:54:43 :: NetGear_Async ::  DEBUG   :: Launching NetGear_Async asynchronous generator!
11:54:43 ::   WriteGear   ::  DEBUG   :: Compression Mode is enabled therefore checking for valid FFmpeg executable.
11:54:43 ::   WriteGear   ::  DEBUG   :: Output Parameters: {}
11:54:43 ::    Helper     ::  DEBUG   :: Final FFmpeg Path: ffmpeg
11:54:43 ::    Helper     ::  DEBUG   :: FFmpeg validity Test Passed!
11:54:43 ::    Helper     ::  DEBUG   :: Found valid FFmpeg Version: `b'5.0.1'` installed on this system
11:54:43 ::   WriteGear   ::  DEBUG   :: Found valid FFmpeg executable: `ffmpeg`.
11:54:43 ::   WriteGear   ::  DEBUG   :: Compression Mode with FFmpeg backend is configured properly.
11:54:43 :: NetGear_Async ::  DEBUG   :: Successfully binded to address: tcp://192.168.0.12:8081 with pattern: 2.
11:54:43 :: NetGear_Async :: CRITICAL :: Receive Mode is activated successfully!
11:54:53 ::   WriteGear   ::  DEBUG   :: InputFrame => Height:720 Width:1280 Channels:3
11:54:53 ::   WriteGear   ::  DEBUG   :: Executing FFmpeg command: `ffmpeg -y -f rawvideo -vcodec rawvideo -s 1280x720 -pix_fmt bgr24 -i - -vcodec libx264 -crf 18 -preset fast /Users/Iacopo/Documents/GitHub/gunner/gunner/netgear/Output.mp4`
ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 13.1.6 (clang-1316.0.21.2)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: 552960 kb/s
  Stream #0:0: Video: rawvideo (BGR[24] / 0x18524742), bgr24, 1280x720, 552960 kb/s, 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
[libx264 @ 0x113f053f0] using cpu capabilities: ARMv8 NEON
[libx264 @ 0x113f053f0] profile High 4:4:4 Predictive, level 3.1, 4:4:4, 8-bit
[libx264 @ 0x113f053f0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=15 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/Users/Iacopo/Documents/GitHub/gunner/gunner/netgear/Output.mp4':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv444p(tv, progressive), 1280x720, q=2-31, 25 fps, 12800 tbn
    Metadata:
      encoder         : Lavc59.18.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
Traceback (most recent call last):     0kB time=00:00:00.08 bitrate=   4.8kbits/s speed=0.0781x    
  File "client.py", line 44, in <module>
    client.loop.run_until_complete(main())
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "client.py", line 27, in main
    async for frame in client.recv_generator():
  File "/Users/Iacopo/Documents/GitHub/gunner/venv/lib/python3.8/site-packages/vidgear/gears/asyncio/netgear_async.py", line 555, in recv_generator
    datamsg_encoded = await asyncio.wait_for(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
(venv) Iacopo@MacBook-Pro netgear % frame=   67 fps=4.0 q=-1.0 Lsize=    1740kB time=00:00:02.56 bitrate=5567.6kbits/s speed=0.155x    
video:1738kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.089490%
[libx264 @ 0x113f053f0] frame I:8     Avg QP:15.22  size: 96547
[libx264 @ 0x113f053f0] frame P:28    Avg QP:19.69  size: 22807
[libx264 @ 0x113f053f0] frame B:31    Avg QP:21.05  size: 11884
[libx264 @ 0x113f053f0] consecutive B-frames: 32.8% 14.9%  4.5% 47.8%
[libx264 @ 0x113f053f0] mb I  I16..4: 19.5% 48.0% 32.5%
[libx264 @ 0x113f053f0] mb P  I16..4:  6.7% 21.5%  1.8%  P16..4: 21.1% 10.8%  4.6%  0.0%  0.0%    skip:33.6%
[libx264 @ 0x113f053f0] mb B  I16..4:  2.6%  7.7%  1.6%  B16..8: 25.5%  9.9%  0.8%  direct: 7.4%  skip:44.5%  L0:57.6% L1:32.8% BI: 9.6%
[libx264 @ 0x113f053f0] 8x8 transform intra:61.1% inter:55.1%
[libx264 @ 0x113f053f0] coded y,u,v intra: 66.5% 43.1% 38.1% inter: 16.7% 8.8% 7.3%
[libx264 @ 0x113f053f0] i16 v,h,dc,p: 22% 25% 11% 41%
[libx264 @ 0x113f053f0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 20% 21% 17%  6%  7%  7%  8%  8%  8%
[libx264 @ 0x113f053f0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 21% 17% 12%  7%  9%  9%  7% 10%  8%
[libx264 @ 0x113f053f0] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x113f053f0] ref P L0: 84.4% 15.6%
[libx264 @ 0x113f053f0] ref B L0: 92.4%  7.6%
[libx264 @ 0x113f053f0] ref B L1: 95.6%  4.4%
[libx264 @ 0x113f053f0] kb/s:5311.62
```

### Python Code

```python
client.py

from vidgear.gears.asyncio import NetGear_Async
from vidgear.gears import WriteGear

import cv2
import asyncio

client = NetGear_Async(
    address="192.168.0.12",
    port="8081",
    protocol="tcp",
    pattern=2,
    receive_mode=True,
    logging=True,
).launch()


writer = WriteGear(output_filename="Output.mp4", logging=True)


async def main():
    async for frame in client.recv_generator():
        writer.write(frame)
        cv2.imshow("Output Frame", frame)
        key = cv2.waitKey(1) & 0xFF
        await asyncio.sleep(0)


if __name__ == "__main__":
    asyncio.set_event_loop(client.loop)
    try:
        client.loop.run_until_complete(main())
    except (KeyboardInterrupt, SystemExit):
        pass

    cv2.destroyAllWindows()
    client.close()
    writer.close()


server.py
```python
import os
import asyncio

from vidgear.gears.asyncio import NetGear_Async


if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(__file__))
    INPUT = "test_video.mp4"
    server = NetGear_Async(
        source=INPUT,
        address="192.168.0.12",
        port="8081",
        protocol="tcp",
        pattern=2,
        logging=True,
    ).launch()

    asyncio.set_event_loop(server.loop)
    try:
        server.loop.run_until_complete(server.task)
    except (KeyboardInterrupt, SystemExit):
        pass
    finally:
        server.close()
```
```


### VidGear Version

0.2.6

### Python version

3.8

### OpenCV version

4.6.0

### Operating System version

macOS Monterey 12.4, M1

### Any other Relevant Information?

_No response_

**Comment by abhiTronix** [comment]
> `pattern=2`

@ginwakeup This might be the problem,  The `pattern=2` i.e. PUB/SUB pattern is not adequate for synchronized frame transfer, consider it like UDP where Server is unaware of state of Client, and any packet drops are simply discarded. So if a packet lost on the way to Client, both Server and Client forgets about it, and you left with corrupted frames which WriteGear cannot write to a file(leads to this issue).

### Solution
Kindly switch to more stable and synchronized patterns such as `pattern=0` (i.e. PAIR) or `pattern=1` (i.e. REP/REQ).

**Comment by ginwakeup** [comment]
> > `pattern=2`
> 
> @ginwakeup This might be the problem, The `pattern=2` i.e. PUB/SUB pattern is not adequate for synchronized frame transfer, consider it like UDP where Server is unaware of state of Client, and any packet drops are simply discarded. So if a packet lost on the way to Client, both Server and Client forgets about it, and you left with corrupted frames which WriteGear cannot write to a file(leads to this issue).
> 
> ### Solution
> Kindly switch to more stable and synchronized patterns such as either `pattern=0` (i.e. PAIR) or `pattern=1` (i.e. REP/REQ) on both Server and Client

Hey @abhiTronix,

thanks for replying, pattern=0 indeed works fine.
The video is received, by the way the size is different and the video still can't be played in Quicktime.

Original video: 5.3MB
Transferred Video: 7.9MB


Full log:

```
/Users/Iacopo/Documents/GitHub/gunner/venv/bin/python /Users/Iacopo/Documents/GitHub/gunner/gunner/netgear/client.py
13:35:05 ::    Helper     ::   INFO   :: Running VidGear Version: 0.2.6
13:35:05 :: NetGear_Async ::   INFO   :: Using `Loop` event loop for this process.
13:35:05 :: NetGear_Async ::  DEBUG   :: Launching NetGear_Async asynchronous generator!
13:35:05 ::   WriteGear   ::  DEBUG   :: Compression Mode is enabled therefore checking for valid FFmpeg executable.
13:35:05 ::   WriteGear   ::  DEBUG   :: Output Parameters: {}
13:35:05 ::    Helper     ::  DEBUG   :: Final FFmpeg Path: ffmpeg
13:35:05 ::    Helper     ::  DEBUG   :: FFmpeg validity Test Passed!
13:35:05 ::    Helper     ::  DEBUG   :: Found valid FFmpeg Version: `b'5.0.1'` installed on this system
13:35:05 ::   WriteGear   ::  DEBUG   :: Found valid FFmpeg executable: `ffmpeg`.
13:35:05 ::   WriteGear   ::  DEBUG   :: Compression Mode with FFmpeg backend is configured properly.
13:35:05 :: NetGear_Async ::  DEBUG   :: Successfully binded to address: tcp://192.168.201.5:8081 with pattern: 0.
13:35:05 :: NetGear_Async :: CRITICAL :: Receive Mode is activated successfully!
13:35:05 ::   WriteGear   ::  DEBUG   :: InputFrame => Height:720 Width:1280 Channels:3
13:35:05 ::   WriteGear   ::  DEBUG   :: Executing FFmpeg command: `ffmpeg -y -f rawvideo -vcodec rawvideo -s 1280x720 -pix_fmt bgr24 -i - -vcodec libx264 -crf 18 -preset fast /Users/Iacopo/Documents/GitHub/gunner/gunner/netgear/Output.mp4`
ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 13.1.6 (clang-1316.0.21.2)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: 552960 kb/s
  Stream #0:0: Video: rawvideo (BGR[24] / 0x18524742), bgr24, 1280x720, 552960 kb/s, 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
[libx264 @ 0x123e07b50] using cpu capabilities: ARMv8 NEON
[libx264 @ 0x123e07b50] profile High 4:4:4 Predictive, level 3.1, 4:4:4, 8-bit
[libx264 @ 0x123e07b50] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=15 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/Users/Iacopo/Documents/GitHub/gunner/gunner/netgear/Output.mp4':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv444p(tv, progressive), 1280x720, q=2-31, 25 fps, 12800 tbn
    Metadata:
      encoder         : Lavc59.18.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
13:35:10 :: NetGear_Async ::   INFO   :: Termination signal received from server!
13:35:10 :: NetGear_Async ::  DEBUG   :: Terminating various Receive Mode Processes. Please wait.
13:35:10 :: NetGear_Async :: CRITICAL :: Receive Mode successfully terminated!
13:35:10 ::   WriteGear   ::  DEBUG   :: Terminating WriteGear Processes.
frame=  739 fps=155 q=-1.0 Lsize=    7738kB time=00:00:29.44 bitrate=2153.1kbits/s speed=6.17x    
video:7730kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.099108%
[libx264 @ 0x123e07b50] frame I:8     Avg QP:11.45  size:129774
[libx264 @ 0x123e07b50] frame P:403   Avg QP:16.63  size: 13946
[libx264 @ 0x123e07b50] frame B:328   Avg QP:20.92  size:  3830
[libx264 @ 0x123e07b50] consecutive B-frames: 38.3%  6.0%  4.9% 50.9%
[libx264 @ 0x123e07b50] mb I  I16..4: 20.5% 26.8% 52.7%
[libx264 @ 0x123e07b50] mb P  I16..4:  1.7%  3.9%  0.4%  P16..4: 33.0% 10.7%  4.2%  0.0%  0.0%    skip:46.1%
[libx264 @ 0x123e07b50] mb B  I16..4:  0.3%  0.9%  0.3%  B16..8: 21.6%  4.6%  0.4%  direct: 3.4%  skip:68.6%  L0:55.0% L1:35.5% BI: 9.5%
[libx264 @ 0x123e07b50] 8x8 transform intra:55.8% inter:62.2%
[libx264 @ 0x123e07b50] coded y,u,v intra: 61.7% 39.6% 36.7% inter: 10.5% 6.0% 4.7%
[libx264 @ 0x123e07b50] i16 v,h,dc,p: 23% 26% 16% 36%
[libx264 @ 0x123e07b50] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 24% 21% 23%  4%  5%  5%  5%  6%  6%
[libx264 @ 0x123e07b50] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 22% 19% 14%  7%  8%  8%  7%  8%  8%
[libx264 @ 0x123e07b50] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x123e07b50] ref P L0: 75.3% 24.7%
[libx264 @ 0x123e07b50] ref B L0: 91.7%  8.3%
[libx264 @ 0x123e07b50] ref B L1: 97.3%  2.7%
[libx264 @ 0x123e07b50] kb/s:2142.06

Process finished with exit code 0
```

Thanks!

**Comment by abhiTronix** [comment]
> The video is received, by the way the size is different and 

The depends upon framerate. But size can never be same as original if you're dealing with frame-by-frame encoding. So you can ignore it.

> the video still can't be played in Quicktime.

That is because QuickTime is a dumb player(literally) also [elaborated on in the official FFmpeg Wiki](https://trac.ffmpeg.org/wiki/Encode/H.264#Encodingfordumbplayers) under the heading **"Encoding for dumb players"**. I'm quoting the official docs:

> You may need to use `-pix_fmt yuv420p` for your output to work in QuickTime and most other players. These players only supports the YUV planar color space with 4:2:0 chroma subsampling for H.264 video. Otherwise, depending on your source, ffmpeg may output to a pixel format that may be incompatible with these players.

So add `-pix_fmt yuv420p` to `output_params` parameter in WriteGear API to resolve this issue as follows:

```python
from vidgear.gears.asyncio import NetGear_Async
from vidgear.gears import WriteGear

import cv2
import asyncio

client = NetGear_Async(
    address="192.168.0.12",
    port="8081",
    protocol="tcp",
    pattern=2,
    receive_mode=True,
    logging=True,
).launch()


# retrieve framerate from CamGear Stream and pass it as `-input_framerate` parameter
output_params = {"-pix_fmt": "yuv420p"}

# Define writer with defined parameters and suitable output filename
writer = WriteGear(output_filename="Output.mp4", logging=True, **output_params)


async def main():
    async for frame in client.recv_generator():
        writer.write(frame)
        cv2.imshow("Output Frame", frame)
        key = cv2.waitKey(1) & 0xFF
        await asyncio.sleep(0)


if __name__ == "__main__":
    asyncio.set_event_loop(client.loop)
    try:
        client.loop.run_until_complete(main())
    except (KeyboardInterrupt, SystemExit):
        pass

    cv2.destroyAllWindows()
    client.close()
    writer.close()
```

**Comment by ginwakeup** [comment]
That's great, thank you very much!
